[[redirects]]
from = '/*'
to = '/https://fun-together.herokuapp.com'
status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"